name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Validate PHP syntax
      run: |
        find php/src -name "*.php" -print0 | xargs -0 -n1 php -l


  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker images
      run: |
        docker build -t zeeshankhan299/php-apache-app:latest -f php/Dockerfile ./php

    - name: Push Docker images
      run: |
        docker push zeeshankhan299/php-apache-app:latest

  # deploy-to-staging:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-docker

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Deploy to staging
  #     run: |
  #       # ssh user@staging-server << 'EOF'
  #       # docker pull zeeshankhan299/php-apache-app:latest
  #       # docker pull zeeshankhan299/mysql:latest
  #       # docker-compose up -d
  #       EOF
